### ISSUE TITLE
Feature request: add custom domain support

### ISSUE THREAD

**Issue by Robin-Wils** [Munter/netlify-plugin-checklinks#206]
You can set a custom domain in Netlify. 

My absolute URLs include that custom domain. The checklinks plugin throws the error "text data outside of root node." when I run it.

It is likely caused by that custom domain. I believe that one way to fix this is to replace the baseURL (domain name) from the URL and check by the URLs by relative path. I might be wrong though.

**Comment by Munter** [comment]
Your custom domain is exposed as an environment variable in the netlify build pipeline, so plugins have access to it. It was supposed to work just out of the box, so I'll mark this one as a bug

**Comment by Robin-Wils** [comment]
I didn't set any environment variables, so maybe I should set one?

**Comment by Munter** [comment]
If your custom domain is set up in the netlify admin area then it is already exposed as an environment variable in the build pipeline the build plugins hook into
