### ISSUE TITLE
Readme: Image Broken

### ISSUE THREAD

**Issue by ayushxx7** [Munter/netlify-plugin-checklinks#556]
![image](https://user-images.githubusercontent.com/16764027/129171038-3e6fa5d1-8daf-41c2-8d55-400de038d086.png)

Please check.

**Comment by Munter** [comment]
The badges come from third party services, that are not always completely reliable. At this moment, that badge is not failing for me, but I have definitely seen it do, like your screenshot shows. I don't think there's much I can do other than remove them
