### ISSUE TITLE
failed deployment due to plugin error

### ISSUE THREAD

**Issue by kirixvelu** [Munter/netlify-plugin-checklinks#582]
1. Installed via Netlify dashboard, failed
2. Enabled plugin at toml, still failed

**Comment by Munter** [comment]
Hi @kiri-vadivelu 

Could you help us a bit with what part of the lifecycle the plugin fails in and what error output you are seeing?

**Comment by kirixvelu** [comment]
So sorry @Munter, I should have investigated. I will try on another site and will update further on the issue if I still experienced again. For now, I will close the issue.

**Comment by kirixvelu** [comment]
Resolved deployment error by uninstalling the plugin. Error to be investigated further in the future deployment.
